<!DOCTYPE html><html class="no-webp" lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="assets/css/first_styles.min.css" media="none" onload="media='all'"><link rel="stylesheet" href="assets/css/1_basic_components/reset_css.min.css" media="none" onload="media='all'"><link rel="shortcut icon" href="assets/img/favicon.svg" type="image/x-icon"><title>Positivus</title><style>body  {margin:0}.preloader {position:fixed;left:0;top:0;right:0;bottom:0;background:#111;z-index:1001;}.preloader__row{position:relative;top:50%;left:50%;width:70px;height:70px;margin-top:-35px;margin-left:-35px;text-align:center;animation:preloader-rotate 1s infinite linear;}.preloader__item{position:absolute;display:inline-block;top:0;background-color:#00c2d0;border-radius:100%;width:35px;height:35px;animation:preloader-bounce 1s infinite ease-in-out}.preloader__item:last-child{top:auto;bottom:0;animation-delay:-1s}@keyframes preloader-rotate{100%{transform:rotate(360deg);}} @keyframes preloader-bounce{0%,100%{transform:scale(0);}50%{transform:scale(1)}} .loaded_hiding .preloader{transition:0.3s opacity;opacity:0}.loaded .preloader{display:none}
</style><!-- Демонстрационный скрипт оптимизации изображений--><script src="assets/js/libs/image-optimization/demo-image-optimization.js"></script><!-- Подключение системы оптимизации изображений--><script src="assets/js/libs/image-optimization/image-format-selector.js" type="module"></script><script src="assets/js/libs/image-optimization/image-optimization-integration.js" type="module"></script><!-- Подключение скрипта определения форматов изображений--><script src="assets/js/libs/image-optimization/image-format-detector.js" type="module"></script><script src="assets/js/first_script.js" type="module"></script><script async="">window.onload = function() {
document.body.classList.add('loaded_hiding');
window.setTimeout(function() {
document.body.classList.add('loaded');
document.body.classList.remove('loaded_hiding');
}, 500);
}

</script></head><body><div class="preloader"><div class="preloader__row"><div class="preloader__item"></div><div class="preloader__item"></div><div class="preloader__item"></div><div class="preloader__item"></div></div></div><div class="header"><div class="header__inner container"><a class="header__logo logo" href="/"><img class="logo__img" src="assets/img/1_header/logo.svg" alt="positivus" width="220" height="36" loading="lazy"></a><img src="assets/img/1_header/webp/1.webp" data-avif-src="assets/img/1_header/avif/1.avif" data-avif-priority="1" data-webp-src="assets/img/1_header/webp/1.webp" data-webp-priority="2" data-original-src="assets/img/1_header/1.png" data-original-priority="3" data-original-ext="png"><nav class="header__menu hidden-mobile"><ul class="header__menu-list"> <li class="header__menu-item"> <a class="header__menu-link" href="/">About us</a></li><li class="header__menu-item"> <a class="header__menu-link" href="/">Services</a></li><li class="header__menu-item"> <a class="header__menu-link" href="/">Use Cases</a></li><li class="header__menu-item"> <a class="header__menu-link" href="/">Pricing</a></li><li class="header__menu-item"> <a class="header__menu-link" href="/">Blog</a></li></ul></nav><button class="header__button button button--transparent hidden-mobile" type="button">Request a quote</button><button class="header__burger-button burger-button visible-mobile" type="button" onClick="mobileOverlay.showModal()"><span class="visually-hidden">open navigation menu </span></button></div></div><dialog class="mobile-overlay visible-mobile" id="mobileOverlay"> <form class="mobile-overlay__close-button-wrapper" method="dialog"><button class="mobile-overlay__close-button cross-button" type="submit"><span class="visually-hidden">Close navigation menu</span></button></form><div class="mobile-overlay__body"> <li class="mobile-overlay__item">    <a class="mobile-overlay__link" href="/">About Us</a></li><li class="mobile-overlay__item">    <a class="mobile-overlay__link" href="/">Services </a></li><li class="mobile-overlay__item">    <a class="mobile-overlay__link" href="/">Use Cases </a></li><li class="mobile-overlay__item">    <a class="mobile-overlay__link" href="/">Pricing </a></li><li class="mobile-overlay__item">  <a class="mobile-overlay__link" href="/">Blog</a></li></div></dialog><script src="assets/js/1_basic_components/jquery/jquery.min.js"></script><script src="https://unpkg.com/imask@6.4.2/dist/imask.js"></script><script src="assets/js/1_basic_components/slickslider/slick.min.js"></script><script src="assets/js/map.js" type="module"></script><script src="assets/js/second_script.js" type="module"></script><script async>function appendToHead(a,c){
    if("css"==a)
    {var b=document.createElement("link");
    b.rel="stylesheet",
    b.href=c,document.head.appendChild(b)
    }
    if("js"==a||"javascript"==a){
        var d=document.createElement("script");
        d.src=c,document.head.appendChild(d)}
    }

appendToHead('css', 'assets/css/second_styles.min.css');</script><script></script></body></html>